version: "3.8"

networks:
  vlds_network:
    driver: bridge

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vlds
    networks:
      - vlds_network
    ports:
      - "3306:3306"
    volumes:
      - "./sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - vlds_network

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - vlds_network

  api:
    build:
      context: api/docker/development/nginx
    ports:
      - "8081:80"
    volumes:
      - ./api:/app
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: api/docker/development/php-fpm
    volumes:
      - ./api:/app

  api-php-cli:
    build:
      context: api/docker/development/php-cli
    volumes:
      - ./api:/app
