version: "3.8"
services:
  frontend:
    build:
      context: frontend/docker/development/nginx
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app

  api:
    build:
      context: api/docker/development/nginx
    ports:
      - "8081:80"
    volumes:
      - ./api:/app
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: api/docker/development/php-fpm
    volumes:
      - ./api:/app

  api-php-cli:
    build:
      context: api/docker/development/php-cli
    volumes:
      - ./api:/app

