version: "3.8"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vlds
    ports:
      - "3306:3306"
    volumes:
      - "./sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql"

  frontend:
    build:
      context: frontend/docker/development/nginx
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app

  api:
    build:
      context: api/docker/development/nginx
    ports:
      - "8081:80"
    volumes:
      - ./api:/app
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: api/docker/development/php-fpm
    volumes:
      - ./api:/app

  api-php-cli:
    build:
      context: api/docker/development/php-cli
    volumes:
      - ./api:/app

